### PR TITLE
Issue #87: Prevent leakage of AdaptableBus threads after closing the client

### LINKED ISSUE #87: java ditto-client threads leakage
Steps executed:

- Open java ditto-client
- call registerForThingChanges
- destroy the client

Every DittoClients seems to occupy ~10 threads in this scenario
When all clients are destroyed, the following threads are still open

| Number of opened clients | Number of opened threads | Number of ditto-client--adaptable-bus threads after destroy| Number of pool-X-thread-Y threads after destroy|
| ------------- | ------------- | ------------- | ------------- |
| 10  | 102 | 22 | 10 |
| 20  | 202 | 42 | 20 |
| 100  | 1002 | 202 | 100 |

The district thread stacks are as follow (if needed I can upload the whole stack trace)

```
"ditto-client--adaptable-bus-74ef6b92-2a09-4b4f-ad24-c3b3689880c7-1" Id=1406 WAITING on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@2f5ac102
	at sun.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@2f5ac102
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1081)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	...

"ditto-client--adaptable-bus-0d61b4fa-984c-4bdf-abf0-f06f951e78f8-2" Id=1396 WAITING on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@895416d
	at sun.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@895416d
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1088)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	...

"pool-99-thread-1" Id=1394 WAITING on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@71a06021
	at sun.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@71a06021
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

### PR DESCRIPTION
**Pull request by DerSchwilk**
Until now the MessagingProvider was closed when the client was destroyed. The executor of the MessagingProvider's AdaptableBus was left open and caused blocked threads after destruction of the client.

This fixes this behavior by closing the AdaptableBus executor when closing the MessagingProvider.

Signed-off-by: David Schwilk <david.schwilk@bosch.io>

Fixes #87

### CODE REVIEW

File: java/src/main/java/org/eclipse/ditto/client/internal/bus/AdaptableBus.java [hunk 1]
```diff
@@ -109,6 +109,13 @@ SubscriptionId subscribeForAdaptableWithTimeout(Classification tag,
      */
     boolean unsubscribe(@Nullable SubscriptionId subscriptionId);
 
+    /**
+     * Closes the executor of the adaptable bus .
+     *
+     * @since 1.2.2
```
Comment (thjaeckle) [inline java/src/main/java/org/eclipse/ditto/client/internal/bus/AdaptableBus.java:115]: the `@since` can be removed as this is in the `internal` package.
`@since` should also only be done for major versions ( e.g. `@since 1.3.0`)

File: java/src/main/java/org/eclipse/ditto/client/DisconnectedDittoClient.java [hunk 2]
```diff
@@ -0,0 +1,34 @@
...
+ * http://www.eclipse.org/legal/epl-2.0
+ *
+ * SPDX-License-Identifier: EPL-2.0
+ */
+package org.eclipse.ditto.client;
+
+import java.util.concurrent.CompletionStage;
+
+/**
+ * Client interface before connecting.
```
Comment (thjaeckle) [inline java/src/main/java/org/eclipse/ditto/client/DisconnectedDittoClient.java:18]: Could you please add `@since 1.3.0` annotation?

**Comment by DerSchwilk** [comment]
Reviewed changes made by @yufei-cai. LGTM :+1:
